'use client';
import { ALLERGENS,type AllergyProfile } from '@/lib/group-types';
export function AllergyPicker({value,onChange,privateSharing=true}:{value:AllergyProfile;onChange:(v:AllergyProfile)=>void;privateSharing?:boolean}){
 return <fieldset className="space-y-3"><legend className="mb-2 font-semibold">食物アレルギー</legend>
 <div className="flex flex-wrap gap-2">{([['unanswered','未回答'],['none','なし'],['selected','選択する']] as const).map(([key,label])=><button type="button" key={key} aria-pressed={value.status===key} className={`rounded-full border px-4 py-2 text-sm ${value.status===key?'border-[#1f4b46] bg-[#1f4b46] text-white':'bg-white'}`} onClick={()=>onChange({...value,status:key,items:key==='selected'?value.items:[],note:key==='selected'?value.note:'',consent:false})}>{label}</button>)}</div>
 {value.status==='selected'&&<><div className="flex flex-wrap gap-2">{ALLERGENS.map(item=><label key={item} className={`inline-flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-2 text-sm ${value.items.includes(item)?'border-[#1f4b46] bg-[#e8eee9]':'bg-white'}`}><input type="checkbox" checked={value.items.includes(item)} onChange={e=>onChange({...value,items:e.target.checked?[...value.items,item]:value.items.filter(x=>x!==item)})}/>{item}</label>)}</div><label className="block text-sm">補足（任意・400文字まで）<textarea className="enc-input mt-1 min-h-20" maxLength={400} value={value.note} onChange={e=>onChange({...value,note:e.target.value})} placeholder="避けたい食材や、店舗へ確認してほしいこと"/></label>{privateSharing&&<label className="flex items-start gap-2 text-sm"><input type="checkbox" className="mt-1" checked={value.consent} onChange={e=>onChange({...value,consent:e.target.checked})}/><span>この内容を幹事に共有することに同意します。ほかの参加者やAIには送信しません。</span></label>}</>}
 <p className="text-xs leading-5 text-[#687370]">選択肢は入力補助です。対応の可否や調理時の混入については、幹事から店舗へ確認してください。{!privateSharing&&'この画面で選んだ内容は端末に保存せず、AIにも送りません。'}</p>
 </fieldset>
}
