'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft,Copy,MessageCircle,RefreshCw,Send,Users,Settings2 } from 'lucide-react';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { EMPTY_ALLERGY,type AllergyProfile,type GroupView,type Reservation } from '@/lib/group-types';
import { AllergyPicker } from './allergy-picker';
import { ReservationCard,ReservationFields } from './reservation';
export function GroupRoom({id}:{id:string}){
 const router=useRouter();
 const [data,setData]=useState<GroupView|null>(null),[loading,setLoading]=useState(true),[join,setJoin]=useState(false),[invite,setInvite]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[text,setText]=useState(''),[profileOpen,setProfileOpen]=useState(false),[profile,setProfile]=useState<AllergyProfile>(EMPTY_ALLERGY),[editOpen,setEditOpen]=useState(false),[draft,setDraft]=useState<Reservation|null>(null),[inviteOpen,setInviteOpen]=useState(false),[inviteLink,setInviteLink]=useState(''),[destructive,setDestructive]=useState<'leave'|'delete'|null>(null);
 const requestKey=useRef<string|null>(null);const version=useRef(0);const pending=useRef(false);
 const refresh=useCallback(async()=>{const r=await fetch(`/api/groups/${id}`,{cache:'no-store'});const body=await r.json();if(r.status===401){setJoin(true);setData(null);return}if(!r.ok)throw new Error(body.error);setData(body);setJoin(false)},[id]);
 useEffect(()=>{let active=true;const fragment=new URLSearchParams(window.location.hash.slice(1)).get('invite')||'';
 // The invite stays in memory, not the URL or referrer, after loading.
 // Hydrate the URL fragment once; it is unavailable during server rendering.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 if(fragment){setInvite(fragment);history.replaceState(null,'',window.location.pathname)}
 const saved=sessionStorage.getItem(`encopa-invite-${id}`);if(saved){setInviteLink(`${location.origin}/groups/${id}#invite=${encodeURIComponent(saved)}`);sessionStorage.removeItem(`encopa-invite-${id}`)}
 const run=()=>refresh().catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});void run();const tick=setInterval(()=>{if(!document.hidden&&!pending.current)void run()},15000);return()=>{active=false;clearInterval(tick)};
 },[id,refresh]);
 async function action(body:Record<string,unknown>){const r=await fetch(`/api/groups/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw new Error(value.error);return value}
 async function perform(fn:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'操作できませんでした。')}finally{pending.current=false;setBusy(false)}}
 async function joinGroup(e:React.FormEvent){e.preventDefault();await perform(async()=>{await action({action:'join',invite,name});setInvite('');await refresh()})}
 async function send(e:React.FormEvent){e.preventDefault();if(!text.trim())return;await perform(async()=>{requestKey.current??=crypto.randomUUID();await action({action:'message',text,requestKey:requestKey.current});setText('');requestKey.current=null;await refresh()})}
 async function copyInvite(){await perform(async()=>{let link=inviteLink;if(!link){const value=await action({action:'invite'});link=`${location.origin}/groups/${id}#invite=${encodeURIComponent(value.invite)}`;setInviteLink(link)}try{await navigator.clipboard.writeText(link);setNotice('招待リンクをコピーしました。参加してほしい人にだけ共有してください。')}catch{setNotice('下のリンクを選択してコピーしてください。')}setInviteOpen(true)})}
 const owner=data?.me.role==='owner';
 return <main className="min-h-screen bg-[#f7f5ef] text-[#1e2928]"><header className="border-b border-[#1e2928]/10 bg-[#f7f5ef]"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-4 sm:px-8"><Link href="/" className="flex items-center gap-2 font-bold tracking-wider"><ArrowLeft size={16}/> ENCOPA</Link><span className="text-xs text-[#687370]">会のグループ</span></div></header><div className="mx-auto max-w-6xl px-4 py-7 sm:px-8">
 {error&&<div role="alert" className="mb-4 flex flex-wrap items-center justify-between gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><span>{error}</span><button className="underline" onClick={()=>void perform(refresh)}>再読み込み</button></div>}{notice&&<p role="status" className="mb-4 rounded-xl bg-[#e5eee6] p-4 text-sm">{notice}</p>}
 {loading?<p role="status" className="py-16 text-center">グループを開いています…</p>:join?<section className="mx-auto max-w-lg rounded-[24px] border bg-white p-6 sm:p-8"><MessageCircle className="mb-4 text-[#1f4b46]" size={32}/><h1 className="text-2xl font-semibold">みんなで予定を共有しよう</h1><p className="mt-3 text-sm leading-6 text-[#687370]">参加すると予約内容とチャットを閲覧できます。表示名はグループ内に公開されます。</p>{invite?<form onSubmit={joinGroup} className="mt-6 space-y-4"><label className="block text-sm">表示名<input autoComplete="nickname" required maxLength={30} className="enc-input mt-2" value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={busy} className="enc-primary w-full">{busy?'参加中…':'このグループに参加する'}</button></form>:<p className="mt-6 rounded-xl bg-[#f7f5ef] p-4 text-sm leading-6">幹事から受け取った招待リンクを開いてください。参加済みの場合は、参加したときと同じブラウザを使ってください。</p>}</section>:data&&<>
 <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-xs font-semibold tracking-widest text-[#a85b40]">OUR GATHERING</p><h1 className="break-words text-3xl font-semibold">{data.title}</h1><p className="mt-2 flex items-center gap-2 text-sm text-[#687370]"><Users size={16}/>{data.members.length}人が参加 · {data.me.name}{owner?'（幹事）':''}</p></div><div className="flex flex-wrap gap-2"><button className="enc-secondary" disabled={busy} onClick={()=>void perform(refresh)} aria-label="再読み込み"><RefreshCw size={16}/></button>{owner&&<button className="enc-primary" disabled={busy} onClick={()=>void copyInvite()}><Copy size={16}/>招待リンク</button>}<button className="enc-secondary" onClick={()=>{setProfile(data.me.allergy);setName(data.me.name);setProfileOpen(true)}}>自分の回答</button></div></div>
 <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,380px)_minmax(0,1fr)]"><aside className="space-y-5"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">最新の予約内容</h2>{owner&&<button className="enc-secondary" onClick={()=>{setDraft(data.reservation);version.current=data.version;setEditOpen(true)}}><Settings2 size={15}/>編集</button>}</div><ReservationCard value={data.reservation}/>{owner&&<button className="enc-primary mt-3 w-full" disabled={busy} onClick={()=>void perform(async()=>{await action({action:'share',version:data.version});await refresh();setNotice('この予約内容をチャットへ共有しました。同じ版は重複投稿しません。')})}><Send size={16}/>予約内容をチャットに送る</button>}</section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">参加メンバー</h2><ul className="mt-3 divide-y">{data.members.map(m=><li key={m.id} className="py-3"><div className="flex items-center justify-between gap-2"><span className="min-w-0 break-words text-sm font-medium">{m.name}{m.role==='owner'?' · 幹事':''}</span>{owner&&m.role!=='owner'&&<button className="shrink-0 text-xs text-[#687370] underline" onClick={()=>{if(window.confirm(`${m.name}さんを退出させますか？招待リンクも無効になります。`))void perform(async()=>{await action({action:'remove',memberId:m.id});setInviteLink('');await refresh()})}}>退出</button>}</div>{owner&&m.allergy&&<p className="mt-1 whitespace-pre-wrap break-words text-xs leading-5 text-[#687370]">食物アレルギー：{m.allergy.status==='unanswered'?'未回答':m.allergy.status==='none'?'なし':`${m.allergy.items.join('、')}${m.allergy.note?` / ${m.allergy.note}`:''}`}</p>}</li>)}</ul>{owner&&<p className="mt-3 text-xs leading-5 text-[#687370]">アレルギーの詳細は幹事と本人にだけ表示しています。店舗への確認に使用してください。</p>}</section><p className="text-xs leading-5 text-[#687370]">グループの有効期限：{new Date(data.expiresAt).toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo'})}。招待リンクは7日間有効です。</p><button className="text-sm text-[#855341] underline" onClick={()=>setDestructive(owner?'delete':'leave')}>{owner?'グループを終了して削除':'このグループを退出'}</button></aside>
 <section className="min-w-0 overflow-hidden rounded-[24px] border bg-white"><div className="border-b px-5 py-4"><h2 className="flex items-center gap-2 font-semibold"><MessageCircle size={19}/>みんなのチャット</h2><p className="mt-1 text-xs text-[#687370]">表示中は15秒ごとに更新 · 最新100件</p></div><div className="max-h-[65vh] min-h-64 space-y-5 overflow-y-auto p-4 sm:p-5" aria-label="チャット履歴">{!data.messages.length?<div className="py-12 text-center"><MessageCircle className="mx-auto mb-3 text-[#a5b4ac]" size={32}/><p className="text-sm text-[#687370]">最初のひとことを送ってみましょう。</p></div>:data.messages.map(m=><article key={m.id} className={`flex ${m.authorId===data.me.id?'justify-end':'justify-start'}`}><div className="w-full max-w-[95%] sm:max-w-[88%]"><p className="mb-1 flex flex-wrap gap-x-2 text-xs text-[#687370]"><span className="break-words">{m.author}</span><time>{new Date(m.createdAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></p>{m.kind==='reservation'&&m.reservation?<div><p className="mb-2 text-xs font-semibold text-[#1f4b46]">共有時点の予約内容</p><ReservationCard value={m.reservation} compact/><p className="mt-1 text-xs text-[#687370]">最新情報は「最新の予約内容」を確認してください。</p></div>:<p className={`whitespace-pre-wrap break-words rounded-2xl px-4 py-3 text-sm leading-6 ${m.authorId===data.me.id?'bg-[#e7efe8]':'bg-[#f4f2ec]'}`}>{m.text}</p>}</div></article>)}</div><form onSubmit={send} className="border-t bg-[#faf9f5] p-4"><label className="sr-only" htmlFor="chat-message">メッセージ</label><textarea id="chat-message" className="enc-input min-h-24" maxLength={2000} value={text} onChange={e=>{setText(e.target.value);requestKey.current=null}} placeholder="待ち合わせや、みんなへの連絡"/><div className="mt-3 flex items-center justify-between gap-3"><span className="text-xs text-[#687370]">{text.length} / 2000 · グループ内に公開</span><button disabled={busy||!text.trim()} className="enc-primary"><Send size={16}/>{busy?'送信中…':'送信'}</button></div></form></section></div>
 </>}
 <Dialog open={profileOpen} onOpenChange={setProfileOpen}><DialogContent className="max-h-[90vh] overflow-y-auto bg-[#fbfaf6] sm:max-w-[600px]"><DialogHeader><DialogTitle>自分の回答</DialogTitle><DialogDescription>アレルギーは本人と幹事だけが閲覧できます。未回答に戻すと登録内容を削除します。</DialogDescription></DialogHeader><form className="space-y-5" onSubmit={e=>{e.preventDefault();void perform(async()=>{await action({action:'profile',name,allergy:profile});await refresh();setProfileOpen(false);setNotice('回答を保存しました。')})}}><label className="block text-sm">表示名<input className="enc-input mt-1" value={name} required maxLength={30} onChange={e=>setName(e.target.value)}/></label><AllergyPicker value={profile} onChange={setProfile}/>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button className="enc-primary w-full" disabled={busy}>回答を保存</button></form></DialogContent></Dialog>
 <Dialog open={editOpen} onOpenChange={setEditOpen}><DialogContent className="max-h-[90vh] overflow-y-auto bg-[#fbfaf6] sm:max-w-[600px]"><DialogHeader><DialogTitle>予約内容を更新</DialogTitle><DialogDescription>保存すると参加者全員の予約表示が更新されます。チャットへの投稿は保存後に選べます。</DialogDescription></DialogHeader>{draft&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();void perform(async()=>{await action({action:'reservation',reservation:draft,version:version.current});await refresh();setEditOpen(false);setNotice('予約内容を更新しました。必要に応じてチャットに送ってください。')})}}><ReservationFields value={draft} onChange={setDraft}/>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="enc-primary w-full">変更を保存</button></form>}</DialogContent></Dialog>
 <Dialog open={inviteOpen} onOpenChange={setInviteOpen}><DialogContent className="bg-[#fbfaf6]"><DialogHeader><DialogTitle>参加者を招待</DialogTitle><DialogDescription>リンクを持つ人は参加できます。公開SNSなどには掲載しないでください。</DialogDescription></DialogHeader><textarea readOnly aria-label="招待リンク" className="enc-input min-h-28 break-all" value={inviteLink}/><button className="enc-primary" onClick={()=>void copyInvite()} disabled={busy}>リンクをコピー</button><button className="enc-secondary" disabled={busy} onClick={()=>void perform(async()=>{const v=await action({action:'invite'});setInviteLink(`${location.origin}/groups/${id}#invite=${encodeURIComponent(v.invite)}`);setNotice('新しい招待リンクを発行しました。以前のリンクは使えません。')})}>リンクを再発行（旧リンクを無効化）</button></DialogContent></Dialog>
 <Dialog open={!!destructive} onOpenChange={()=>setDestructive(null)}><DialogContent><DialogHeader><DialogTitle>{destructive==='delete'?'グループを削除しますか？':'グループを退出しますか？'}</DialogTitle><DialogDescription>{destructive==='delete'?'予約内容・参加者の回答・チャットを削除します。この操作は取り消せません。':'自分の回答を削除します。過去のメッセージは退会した参加者として残ります。'}</DialogDescription></DialogHeader><button className="enc-primary" disabled={busy} onClick={()=>void perform(async()=>{await action({action:destructive});router.push('/')})}>{destructive==='delete'?'削除する':'退出する'}</button></DialogContent></Dialog>
 </div></main>
}
